### ISSUE TITLE
about some error

### ISSUE THREAD

**Issue by bilibilijin** [pfeiwu/PalWorld-Server-KeepAlive-script-on-Windows-Server#2]
你好 很感谢你写的脚本，但是我在运行时碰到了一些问题 希望你能帮我解决

`PS C:\Users\Administrator\Desktop> .\script.ps1
所在位置 C:\Users\Administrator\Desktop\script.ps1:62 字符: 6
+     }
+      ~
do 循环中缺少 while 或 until 关键字。
所在位置 C:\Users\Administrator\Desktop\script.ps1:80 字符: 1
+         elseif ($restartPolicyChoice -eq "2")
+               ~
switch 语句的子句中缺少语句块。
所在位置 C:\Users\Administrator\Desktop\script.ps1:122 字符:
+ Write-Host "杈撳叆 '1' - 鏄紝鈥?鈥?- 鍚?
+                   ~~~~~~~~~~~~~~~
字符串缺少终止符: '。
所在位置 C:\Users\Administrator\Desktop\script.ps1:92 字符: 9
+         {
+         ~
语句块或类型定义中缺少右“}”。
所在位置 C:\Users\Administrator\Desktop\script.ps1:66 字符: 1
+ {
+ ~
语句块或类型定义中缺少右“}”。
    + CategoryInfo          : ParserError: (:) [], ParseExcep
    + FullyQualifiedErrorId : MissingWhileOrUntilInDoWhile
`

我也用管理员权限试过了，但不行，希望得到你的尽快回复！

**Comment by pfeiwu** [comment]
看你的报错我好像知道了 应该是编码问题 里面的中文变成乱码 影响了脚本执行

**Comment by pfeiwu** [comment]
可以去系统的区域设置把使用unicode utf8提供全球语言支持这个打开 如果不知道在哪里 可以等我发一个b站视频

**Comment by pfeiwu** [comment]
这个是windows的一个巨坑

**Comment by bilibilijin** [comment]
> 看你的报错我好像知道了 应该是编码问题 里面的中文变成乱码 影响了脚本执行

好的 谢谢回复，我在把脚本从本地复制到服务器的时候会出现乱码，我重新在本地将内容复制进服务器的脚本中就可以了，现在已经可以使用了，感谢你的脚本！
